### ISSUE TITLE
Win7 64bit zip contains nothing but nw.js files

### ISSUE THREAD

**Issue by echoma** [egrcc/Mango#1]
only nw.js default UI is shown, no mango things.  same things happens with 32bit zip file.

**Comment by egrcc** [comment]
I test xp 32bit, win7 32bit, 64bit, all is no problem. Are you test in other machine?

**Comment by MikeAfc** [comment]
楼上两位为嘛不干脆中文交流下。      =。=

**Comment by MikeAfc** [comment]
Why upstairs not jiaoliu in chinese? LOL
