### ISSUE TITLE
pdf导出问题

### ISSUE THREAD

**Issue by okeqinwang** [egrcc/Mango#3]
您好，导出pdf之后 出现这样的格式，请问是什么原因？ 另外 链接不能点击
![image](https://cloud.githubusercontent.com/assets/6440773/8399873/a7fe115a-1e48-11e5-9fd3-fde081be59b6.png)

另：可以添加粘贴上传到七牛云的功能吗

**Comment by egrcc** [comment]
这确实是一个偶尔会出现的bug，原因我也暂时不清楚。

链接不能点击的问题，是因为导出pdf是用的别人写的库 phantom-html2pdf：https://github.com/bauhausjs/phantom-html2pdf
这个库没有实现这个功能，所以导出pdf 并不能保证百分百完美。如果有哪位朋友有更好的推荐，欢迎提出。

关于添加功能，确实还有很多功能是想做的，如果你迫切需要某一功能的话，可以自己尝试修改源代码。

**Comment by okeqinwang** [comment]
已經提交

**Comment by egrcc** [comment]
非常感谢贡献代码。
不过这几天我在忙考试的事情，可能需要过一些时间才能处理。

**Comment by okeqinwang** [comment]
ok
